#!/bin/bash
#
# Sync external skills from other repositories.
# Reads external-skills.yml, clones/pulls repos into references/, and symlinks into setting/skills/.
#

set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
YML_FILE="$DOTFILES_DIR/external-skills.yml"
REF_DIR="$DOTFILES_DIR/references"
SKILLS_DIR="$DOTFILES_DIR/setting/skills"

# ── helpers ──────────────────────────────────────────────────

ensure_link() {
  local src="$1"
  local dst="$2"

  if [ -d "$dst" ] && [ ! -L "$dst" ]; then
    rm -rf "$dst"
  fi

  ln -sfn "$src" "$dst"
  printf '   %s -> %s\n' "$dst" "$src"
}

# Derive a unique directory name from a git URL
# e.g. https://github.com/alice/opencode-skills.git → alice--opencode-skills
repo_dirname() {
  local url="$1"
  local name

  # Strip trailing .git
  name="${url%.git}"
  # Extract owner/repo from URL (handles https and ssh)
  name="$(echo "$name" | grep -oE '[^/:]+/[^/]+$' | tr '/' '--')"

  if [[ -z "$name" ]]; then
    name="$(basename "${url%.git}")"
  fi

  echo "$name"
}

# ── YAML parser ──────────────────────────────────────────────
# Parses the simple external-skills.yml format.
# Outputs tab-separated lines: name\trepo\tpath

parse_skills_yml() {
  local yml="$1"
  local name="" repo="" skill_path=""

  while IFS= read -r line || [[ -n "$line" ]]; do
    # Trim leading whitespace
    local trimmed="${line#"${line%%[![:space:]]*}"}"

    # Skip comments and empty lines
    [[ -z "$trimmed" || "$trimmed" == \#* ]] && continue

    case "$trimmed" in
      "- name: "*)
        # Emit previous entry if complete
        if [[ -n "$name" && -n "$repo" ]]; then
          printf '%s\t%s\t%s\n' "$name" "$repo" "$skill_path"
        fi
        name="${trimmed#- name: }"
        repo=""
        skill_path=""
        ;;
      "name: "*)
        name="${trimmed#name: }"
        ;;
      "repo: "*)
        repo="${trimmed#repo: }"
        ;;
      "path: "*)
        skill_path="${trimmed#path: }"
        ;;
    esac
  done < "$yml"

  # Emit last entry
  if [[ -n "$name" && -n "$repo" ]]; then
    printf '%s\t%s\t%s\n' "$name" "$repo" "$skill_path"
  fi
}

# ── main ─────────────────────────────────────────────────────

sync_external_skills() {
  [[ -f "$YML_FILE" ]] || return 0

  local has_entries=false
  local entry_count=0
  local fail_count=0
  local update_count=0
  local external_names=()

  while IFS=$'\t' read -r name repo skill_path; do
    has_entries=true
    entry_count=$((entry_count + 1))
    external_names+=("$name")

    local dir_name
    dir_name="$(repo_dirname "$repo")"
    local repo_dir="$REF_DIR/$dir_name"

    # Clone or pull
    if [[ -d "$repo_dir/.git" ]]; then
      local before after
      before="$(git -C "$repo_dir" rev-parse HEAD 2>/dev/null)"
      if ! git -C "$repo_dir" pull --ff-only --quiet 2>/dev/null; then
        printf '⚠️  Failed to pull %s\n' "$repo"
        fail_count=$((fail_count + 1))
        continue
      fi
      after="$(git -C "$repo_dir" rev-parse HEAD 2>/dev/null)"
      if [[ "$before" != "$after" ]]; then
        printf '\033[0;32m[dotai]\033[0m Updated %s (%s)\n' "$name" "${after:0:7}"
        update_count=$((update_count + 1))
      fi
    else
      mkdir -p "$REF_DIR"
      if ! git clone --quiet "$repo" "$repo_dir" 2>/dev/null; then
        printf '⚠️  Failed to clone %s\n' "$repo"
        fail_count=$((fail_count + 1))
        continue
      fi
      printf '\033[0;32m[dotai]\033[0m Installed %s\n' "$name"
      update_count=$((update_count + 1))
    fi

    # Resolve source path
    local src="$repo_dir"
    [[ -n "$skill_path" ]] && src="$repo_dir/$skill_path"

    if [[ -d "$src" ]]; then
      ensure_link "$src" "$SKILLS_DIR/$name"
    else
      printf '⚠️  Skill path not found: %s (in %s)\n' "$skill_path" "$repo"
      fail_count=$((fail_count + 1))
    fi
  done < <(parse_skills_yml "$YML_FILE")

  # Auto-generate .gitignore for external skill symlinks
  if [[ ${#external_names[@]} -gt 0 ]]; then
    printf '# Auto-generated by sync-external.sh — do not edit\n' > "$SKILLS_DIR/.gitignore"
    printf '%s\n' "${external_names[@]}" >> "$SKILLS_DIR/.gitignore"
  fi

  if $has_entries && [[ $fail_count -gt 0 ]]; then
    printf '⚠️  %d external skill(s) failed to sync\n' "$fail_count"
  fi
}

sync_external_skills
